1Web/urls.py
from django import urls
from django.conf.urls import include
from django.urls import path
from .views import *
from rest_framework import routers


router = routers.DefaultRouter()
router.register('producto', ProductoViewSet)
router.register('categoria', CategoriaViewSet)
router.register('Ordenes', OrdenViewSet)
router.register('Orden Item', OrdenItemView)


urlpatterns = [
    path('', home, name="home"),
    path('carro/', carro, name="carro"),
    path('contacto', contacto, name="contacto"),
    
    #Catalago
    path('catalogoCuerdas', catalogoCuerdas, name="catalogoCuerdas"),
    path('catalogoPercusion', catalogoPercusion, name="catalogoPercusion"),
    path('catalagoAccesorios', catalogoAccesorios, name="catalagoAccesorios"),
    path('catalagoAmplificadores',catalogoAmpli, name="catalagoAmplificadores"),
    #End of Catalago
    
    #Registro / Login
    path('registro/', registro ,name="registro"),
    #End of Registro

    #API para consultar los productos
    path('api/', include(router.urls)),
    path('silk/', include('silk.urls')),


    path('actualizar_carro/', actualizarCarro, name="actualizar"),
    path('procesar_orden/', procesar_orden, name="orden"),
    path('bodega/', bodega, name="bodega"),


    #vista-admin
    path('informe/', informe, name="informes"),
    path('desempeño/', desempeno, name="tienda"),
    path('listar-producto/', listar_producto, name="listar_producto"),
    path('modificar-producto/<id>/',modificar_producto, name="modificar_producto"),
    path('agregar-producto/',agregar_producto, name="agregar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name="eliminar_producto"),
    #End of Admin    



    #URLS WEBPAY
    path('create/', create, name ="create"),
    path('commit/', webpay_commit, name="commit"),



    #URLS VENDEDOR
    path('ordenes/', listar_ordenes, name="ordenes"),
]


    
    

MusicPro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('1Web.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

1Web/models.py
from django.db import models
from django.contrib.auth.models import User

#las opciones disponibles en tipo consulta
opciones_consultas = [
    [0, "consultas"],
    [1, "reclamos"],
    [2, "reservas"],
    [3, "felicitaciones"]
]


sub_categorias = [
    [0, "Guitarras"],
    [1, "Bajos"],
    [2, "Pianos"],
    [3, "Baterias Acusticas"],
    [4, "Bateria Electronica"],
    [5, "Cabezales"],
    [6, "Cajas"],
    [7, "Audifonos"],
    [8, "Monitores"],
    [9, "Parlantes"],
    [10, "Cables"],
    [11, "Microfonos"],
    [12, "Interfaces"],
    [13, "Mixers"],
]

#Modelo para el usuario logeado

class Usuario(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200)
    def __str__(self):
        return self.name



#modelo para el contacto
class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre




#CUERDAS, PERCUSION, AMPLIFICADORES, ACCESORIOS
class Categoria(models.Model):
    nombre = models.CharField(max_length=200, blank=False, null=False)
    slug = models.SlugField(max_length=255, unique=True)
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['nombre']
    def __str__(self):
        return self.nombre    



#modelo del producto
class Producto(models.Model):
    id = models.AutoField(primary_key = True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True)
    tipo_categoria = models.IntegerField(choices=sub_categorias)
    slug = models.SlugField(max_length=255, unique=True)
    modelo = models.CharField(max_length=250 ,blank= False, null= False)
    marca  = models.CharField(max_length = 200, blank = False, null = False)
    precio = models.IntegerField(blank= False, null= False)
    imagen = models.ImageField(upload_to = "productos/", null=True)
    stock = models.IntegerField(blank= False, null= False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['marca']   


    def __str__(self):
        return self.marca

class Orden(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True, blank=True)
    dia_orden = models.DateTimeField(auto_now_add=True)
    entregado = models.BooleanField(default=False)
    transaccion_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        ordenitem = self.ordenitem_set.all()
        total = sum([item.getTotal for item in ordenitem])
        return total

    @property
    def get_items_total(self):
        ordenitem = self.ordenitem_set.all()
        total = sum([item.cantidad for item in ordenitem])
        return total

class OrdenItem(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.SET_NULL, null=True)
    orden = models.ForeignKey(Orden, on_delete=models.SET_NULL, null=True)
    cantidad = models.IntegerField(default=0, null=True, blank=True)
    added = models.DateTimeField(auto_now_add=True)


    @property
    def getTotal(self):
        total = self.producto.precio * self.cantidad
        return total


class Direccion(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True)
    orden = models.ForeignKey(Orden, on_delete=models.SET_NULL, null=True)
    direccion = models.CharField(max_length=200, null=False)
    ciudad = models.CharField(max_length=250, null=False)
    comuna = models.CharField(max_length=250, null=False)
    codigo_postal = models.CharField(max_length=255, null=False)
    added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.direccion

1Web/forms.py
from django import forms
from .models import Contacto, Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#formulario para contacto
class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ["nombre", "correo", "tipo_consulta", "mensaje", "avisos" ]



class CustomUserCreationForm(UserCreationForm):   
    class Meta:
        model = User
        fields = ['username', 'first_name', "last_name",'email', "password1", "password2"]


    



class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

1Web/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
from .forms import ContactoForm,CustomUserCreationForm, ProductoForm
from rest_framework import viewsets
import requests
from django.contrib import messages
from .serializers import *
from .models import *
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse, response
import json
from django.contrib.auth.models import User
from .filters import ProductoFilter
from transbank.error.transbank_error import TransbankError
from transbank.webpay.webpay_plus.transaction import Transaction
import random
import datetime







#vista para el inicio
def home(request):
    #Vista de los ultimos productos añadidos
    ultimos = Producto.objects.all()[0:4]
    data = {
        'ultimos' : ultimos
    }
    return render(request, "index.html", data)

@login_required(login_url='login')
@permission_required('1Web.view_categoria')
def informe(request):
    return render(request, 'admin/informes.html')

@login_required(login_url='login')
@permission_required('1Web.view_categoria')
def desempeno(request):
    return render(request, 'admin/desempeno.html')

#vista para la api
class ProductoViewSet(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer


class CategoriaViewSet(viewsets.ModelViewSet):
    queryset = Categoria.objects.all()
    serializer_class = CategorySerializer

class OrdenViewSet(viewsets.ModelViewSet):
    queryset = Orden.objects.all()
    serializer_class = OrdenSerializer

class OrdenItemView(viewsets.ModelViewSet):
    queryset = OrdenItem.objects.all()
    serializer_class = OrdenItemSerializer



        


#vista para el contacto
def contacto(request):
    data = {
        'form' : ContactoForm()
    }
    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "FORMULARIO DE CONTACTO ENVIADO"
            messages.success(request,"FORMULARIO DE CONTACTO ENVIADO")
        else:
            data["form"] = formulario
    return render(request,'contacto.html', data)



#vista para registro
def registro(request):
    data = {
        'form': CustomUserCreationForm()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            User =  authenticate(username=formulario.cleaned_data["username"],password =formulario.cleaned_data["password1"])
            login(request, User)
            data["mensaje"] = "Usuario Registrado"
            messages.success(request, "Usuario registrado correctamente.")
            return redirect(to="home")
        data["form"] =  formulario
    return render(request, 'registration/registro.html', data)





#vista para catalogo cuerdas
def catalogoCuerdas(request):
    productos = Producto.objects.all()

    filtro = ProductoFilter(request.GET, queryset=productos)
    productos = filtro.qs

    data = {
        'productos': productos,
        'filtro': filtro
    }
    return render(request, "Catalogo/catalogoCuerdas.html",data)


#vista para catalogo uuerdas
def catalogoPercusion(request):
    productos = Producto.objects.all() # error que no influye

    filtro = ProductoFilter(request.GET, queryset=productos)
    productos = filtro.qs
    data = {
        'productos': productos,
        'filtro':filtro
    }
    return render(request, "Catalogo/catalogoPercusion.html",data)


def catalogoAmpli(request):
    productos = Producto.objects.all() # error que no influye
    filtro = ProductoFilter(request.GET, queryset=productos)
    productos = filtro.qs
    data = {
        'productos': productos,
        'filtro':filtro
    }
    return render(request, "Catalogo/catalogoAmplificadores.html",data)


def catalogoAccesorios(request):
    productos = Producto.objects.all() # error que no influye
    filtro = ProductoFilter(request.GET, queryset=productos)
    productos = filtro.qs
    data = {
        'productos': productos,
        'filtro':filtro
    }
    return render(request, "Catalogo/catalagoAccesorios.html",data)




#vista para listar
@login_required(login_url='login')
@permission_required('1Web.view_producto')
def listar_producto(request):
    response = requests.get('http://127.0.0.1:8000/api/producto/').json()
    return render(request,'GestionProductos/listar.html',{'response':response})


#vista para modificar producto
@login_required(login_url='login')
@permission_required('1Web.update_producto')
def modificar_producto(request,id):
    productos = get_object_or_404(Producto, id=id)
    data = {
        'form': ProductoForm(instance=productos)
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=productos, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            return redirect(to="listar_producto")
        data["form"] = formulario
    return render(request, 'GestionProductos/modificar.html', data)



#vista para agregar producto,las fotos de los productos estan en media 
@login_required(login_url='login')
@permission_required('1Web.add_producto')
def agregar_producto(request):
    #capturo lo del formulario
    data = {
        'form' : ProductoForm()
    }
    #si el formulario esta ingresado envio un mensaje
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            messages.success(request, 'Producto agregado correctamente')
            formulario.save()
            data["mensaje"] = "Producto Almacenado"
        else: 
            data["form"] = formulario
    return render(request,'GestionProductos/agregar.html', data)



#vista para eliminar produco
@login_required(login_url='login')
@permission_required('1Web.delete_producto')
def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    return redirect(to="listar_producto")




#vista para carrito
def carro(request):
    if request.user.is_authenticated:
        usuario = request.user.usuario
        orden, created = Orden.objects.get_or_create(usuario=usuario, entregado=False)
        items = orden.ordenitem_set.all()
        itemsCarro = orden.get_items_total        
    else:
        items = []
        orden = {'get_cart_total':0, 'get_items_total':0}
        itemsCarro = orden['get_items_total'] 

    context = {'items':items, 'orden':orden, 'itemsCarro':itemsCarro}
    return render(request, "carro.html", context)



def bodega(request):
    productos = Producto.objects.all() # error que no influye
    data = {
        'productos': productos
    }
    return render(request, 'bodega/bodega.html', data)




def actualizarCarro(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Accion: ', action)
    print('Producto id', productId)
    
    user = request.user.usuario
    producto = Producto.objects.get(id=productId)
    orden, created = Orden.objects.get_or_create(usuario=user, entregado=False)
    ordenItem, created = OrdenItem.objects.get_or_create(orden=orden, producto=producto)
    if action == 'add':
        messages.success(request, 'Producto Añadido con exito')
        ordenItem.cantidad = (ordenItem.cantidad + 1)
    elif action == 'eliminar':
        messages.info(request, 'Cantidad reducida')
        ordenItem.cantidad = (ordenItem.cantidad - 1)
    ordenItem.save()
    if ordenItem.cantidad <= 0:
        ordenItem.delete()

    return JsonResponse('Producto fue añadido', safe=False)


def procesar_orden(self):
    return JsonResponse('Orden completada', safe=False)




def create(request):
    if request.user.is_authenticated:
        usuario = request.user.usuario
        orden, created = Orden.objects.get_or_create(usuario=usuario, entregado=False)   
        buy_order = str(random.randrange(1000000, 99999999))
        session_id = str(random.randrange(1000000, 99999999))
        amount = orden.get_cart_total
        return_url = 'http://localhost:8000/commit/'

        response = Transaction.create(buy_order, session_id, amount, return_url)
        print(response)
        context = {'response':response}
        return render(request, 'webpay/create.html', context )



def webpay_commit(request ):
    if request.POST['token_ws']:
        transaction_id = datetime.datetime.now().timestamp()
        token = request.POST['token_ws']
        response = Transaction.commit(token=token,)
        
        if request.user.is_authenticated:
            usuario = request.user.usuario
            orden = Orden.objects.get_or_create(usuario=usuario, entregado=False)
            orden.transaccion_id = transaction_id
            orden.entregado = True
            orden.save()
        else:
            print('Usuario no logeado')

        context = {'token':token,'response':response}
        return render(request, 'webpay/commit.html', context) 







@login_required(login_url='login')
@permission_required('1Web.view_orden_item')
def listar_ordenes(request):
    response = requests.get('http://127.0.0.1:8000/api/Orden%20Item/').json()
    return render(request,'Vendedor/listar-orden.html',{'response':response})

    

1Web/templates/GestionProductos/agregar.html
{% load static %} {% block content %}


{% include "admin/dashboard.html" %}
<br>
<div id="contenido">
    {% load crispy_forms_tags %}
    
    <div class="row">
        <div class="col12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2>Agregar Nuevo Producto</h2>
                    <hr>
                    <form action="" method="post" enctype="multipart/form-data" class="was-validated">
                        <!-- token de suguridad -->
                        {% csrf_token %} 
                        
                        {{ form | crispy }}
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <input type="submit" value="Guardar" class="btn btn-primary">
                        </div>
                    </form>

                    <h2>{{mensaje}}</h2>

                </div>
            </div>
        </div>
    </div>
</div>

<script scr="{% static '/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}"></script>

{% if messages %}
{% for mensaje in messages %}
<script type="text/javascript">
  $(function() {
    const Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 3000
    });
    $('.swalDefaultSuccess').click(function() {
      Toast.fire({
        icon: 'success',
        title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
      })
    });
  });
</script>
{% endfor %}
{% endif %}
{% endblock %}

1Web/templates/GestionProductos/listar.html
{% load static %} {% block content %}
{% include "admin/dashboard.html" %}
<head>
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}" href="../../plugins/datatables-responsive/css/responsive.bootstrap4.min.css">

    <script type="text/javascript">
        function eliminarProducto(id) {
            Swal.fire({
                "title": "¿Estas seguro?",
                "text": "Esta accion es irreversible",
                "icon": "warning",
                "showCancelButton":true,
                "cancelButtonText": "No, cancelar",
                "confirmButtonText": "Si, eliminar",
                "confirmButtonColor": "#dc3545"
            })
            .then(function(result) {
                if(result.isConfirmed){
                    window.location.href = "/eliminar-producto/"+id+"/"
                    Swal.fire(
                    'Eliminado:',
                    'El producto ha sido eliminado con exito.',
                    'success'
                )
                }
                
            })
        }

    </script>
</head>

<body>
    <div id="contenido" class="content-wrapper">
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3>Listado de Productos</h3>
                        </div>
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover" >
                                <thead>
                                    <tr>
                                        <th>Modelo</th>
                                        <th>Marca</th>
                                        <th>Precio</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for p in response %}
                                    <tr>
                                        <td>{{ p.marca | title }}</td>
                                        <td>{{ p.modelo | title }}</td>
                                        {% load humanize %}
                                        <td>${{ p.precio | intcomma }}</td>
                                        <td> 
                                            {% if perms.app.change_producto %}
                                            <a href="{% url 'modificar_producto' p.id %}" class="btn btn-info btn-sm">Modificar</a>
                                            {% endif %}
                                            {% if perms.app.delete_producto%}
                                            <a href="#" onclick="eliminarProducto({{p.id}})" class="btn btn-danger btn-sm ml-5">Eliminar</a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>


<!--Scripts para el datatable-->


<!-- jQuery -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<!-- AdminLTE App -->




<script>
  $(function () {
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": true,
      "responsive": true,
    });
  });
</script>


</body>


{% endblock %}

1Web/templates/GestionProductos/modificar.html
{% load static %} {% block content %}

{% include "admin/dashboard.html" %}
{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Editar Producto</h2>
                <hr>
                <form action="" method="post" enctype="multipart/form-data">

                    {%csrf_token %}
                    {{ form | crispy }}
                    
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'listar_producto' %}"><button class="btn btn-secondary">Cancelar</button></a>
                        <br>
                        <input type="submit" value="Editar" class="btn btn-primary">
                    </div>
                </form>

                <h2>{{mensaje}}</h2>

            </div>
        </div>
    </div>
</div>
</div>
<script scr="{% static '/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}"></script>

{% if messages %}
{% for mensaje in messages %}
<script type="text/javascript">
  $(function() {
    const Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 3000
    });
    $('.swalDefaultSuccess').click(function() {
      Toast.fire({
        icon: 'success',
        title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
      })
    });
  });
</script>
{% endfor %}
{% endif %}



{% endblock %}